### ISSUE TITLE
HelloKitty ransomware reported undetected

### ISSUE THREAD

**Issue by pierreroger6466** [SitinCloud/Owlyshield#21]
Somebody reported in malwaretips.com that the HelloKitty is undetected.

**Comment by dlescos** [comment]
Actually it is detected, but with a weak certainty (around 60-65%). The issue lies in `config::Config` defines two thresholds (hardcoded) : 

1. The minimal certainty to decide if a program is a ransomware (0.65),
2. The minimal number of updated files for a prediction to be considered reliable (100).

This behaviour is inherited from the time we were still using MLPs for classification. XGBOOST is way better and we may update thoses constants accordingly. 

Also, model training was done on imbalanced data. We are achieving excellent results by oversampling with [SMOTE](https://arxiv.org/pdf/1106.1813.pdf). We will deploy it once it's been tested on our side.

**Comment by dlescos** [comment]
See commit cd1cb0864cb68a92a6fe656dd14da2e5a724d68e
